- hosts: all
  gather_facts: True
  become: True
  become_user: root
  roles:
    - role: base
    - { role: kubernetes-dnf, when: ansible_pkg_mgr == "dnf" }
    - { role: kubernetes-apt, when: ansible_pkg_mgr == "apt" }
    - role: kubernetes
    - role: home
    - role: joshualund.golang
    - role: dochang.docker